### ISSUE TITLE
vercel provider panics on plan or apply

### ISSUE THREAD

**Issue by stevenceuppens** [vercel/terraform-provider-vercel#11]
vercel provider panics on plan or apply

```
$ terraform plan

...

module.app-www.vercel_project.www: Refreshing state... [id=prj_ebuz3GCJmwd8bUXdfJQW3yctv33u]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).PlanResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-vercel_v0.2.2 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5a151d]

goroutine 75 [running]:
github.com/hashicorp/terraform-plugin-framework/types.SetType.Validate({{0xb58ba0, 0xc000453860}}, {0xc000232e58, 0xc000658368}, {{0x0, 0x0}, {0x0, 0x0}}, 0xc0006630c0)
        github.com/hashicorp/terraform-plugin-framework@v0.5.0/types/set.go:118 +0xbd
github.com/hashicorp/terraform-plugin-framework/tfsdk.State.getAttributeValue({{{0xb72370, 0xc000700c30}, {0x9d44e0, 0xc000202810}}, {0xc000554a50, 0x0, 0x0, {0x0, 0x0}, {0xab4ba2, ...}, ...}}, ...)
        github.com/hashicorp/terraform-plugin-framework@v0.5.0/tfsdk/state.go:95 +0x297
github.com/hashicorp/terraform-plugin-framework/tfsdk.Attribute.modifyPlan({{0xb6e3f8, 0xc0006630c0}, {0x0, 0x0}, {0xab0dda, 0x88}, {0x0, 0x0}, 0x1, 0x0, ...}, ...)
        github.com/hashicorp/terraform-plugin-framework@v0.5.0/tfsdk/attribute.go:491 +0x168
github.com/hashicorp/terraform-plugin-framework/tfsdk.Attribute.modifyPlan({{0x0, 0x0}, {0xb74df0, 0xc00000c8b8}, {0xaad96a, 0x4a}, {0x0, 0x0}, 0x0, 0x1, ...}, ...)
        github.com/hashicorp/terraform-plugin-framework@v0.5.0/tfsdk/attribute.go:569 +0x19e8
github.com/hashicorp/terraform-plugin-framework/tfsdk.Schema.modifyPlan({_, _, _, {_, _}, {_, _}, {_, _}}, {0xb692d8, ...}, ...)
        github.com/hashicorp/terraform-plugin-framework@v0.5.0/tfsdk/schema.go:321 +0x250
github.com/hashicorp/terraform-plugin-framework/tfsdk.(*server).planResourceChange(0xc0003c5a70, {0xb692d8, 0xc00004e7c0}, 0xc00013a7d0, 0xc00065ba10)
        github.com/hashicorp/terraform-plugin-framework@v0.5.0/tfsdk/serve.go:810 +0xe0e
github.com/hashicorp/terraform-plugin-framework/tfsdk.(*server).PlanResourceChange(0xb692d8, {0xb692d8, 0xc00004e700}, 0x5)
        github.com/hashicorp/terraform-plugin-framework@v0.5.0/tfsdk/serve.go:635 +0x90
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).PlanResourceChange(0xc00030e600, {0xb69380, 0xc000554300}, 0xc0002560e0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov6/tf6server/server.go:579 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_PlanResourceChange_Handler({0xa663c0, 0xc00030e600}, {0xb69380, 0xc000554300}, 0xc0005822a0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:363 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00036c8c0, {0xb74ea0, 0xc0001e2820}, 0xc000584000, 0xc0003c5bc0, 0xf7c1a8, 0x0)
        google.golang.org/grpc@v1.43.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00036c8c0, {0xb74ea0, 0xc0001e2820}, 0xc000584000, 0x0)
        google.golang.org/grpc@v1.43.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.43.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.43.0/server.go:919 +0x294

Error: The terraform-provider-vercel_v0.2.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

ERRO[0014] 1 error occurred:
        * exit status 1
          
make: *** [Makefile:43: plan] Error 1
```

**Comment by dglsparsons** [comment]
Hi, thanks for submitting this. 

It looks like the issue is related to https://github.com/hashicorp/terraform-plugin-framework/issues/261 (judging by the stack trace). 

At a guess, do you have a `vercel_project` resource that you have added the `environment` field to?
